import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime, timedelta

def calculate_time_saved(audits):
    """Calculate total time saved based on audit data"""
    if not audits:
        return 0
    
    total_hours = 0
    for audit in audits:
        # Assume each audit saved 15 hours compared to manual
        # This can be refined based on actual data
        predicted = audit.get('predicted_hours', 0)
        if predicted > 0:
            # If we have predicted hours, use that
            total_hours += predicted * 0.6  # Estimated 60% time saved
        else:
            total_hours += 15  # Default estimate
    
    return total_hours

def calculate_cost_savings(hours_saved, hourly_rate=100):
    """Calculate cost savings in dollars"""
    return hours_saved * hourly_rate

def get_monthly_trends(audits):
    """Get monthly trends for key metrics"""
    if not audits:
        return pd.DataFrame()
    
    df = pd.DataFrame(audits)
    df['created_at'] = pd.to_datetime(df['created_at'])
    df['month'] = df['created_at'].dt.strftime('%Y-%m')
    
    monthly = df.groupby('month').agg({
        'match_rate': 'mean',
        'fraud_risk': 'mean',
        'id': 'count'
    }).reset_index()
    
    monthly.columns = ['Month', 'Avg Match Rate', 'Avg Fraud Risk', 'Audit Count']
    return monthly

def get_efficiency_score(audits):
    """Calculate overall efficiency score (0-100)"""
    if not audits:
        return 0
    
    # Factors that contribute to efficiency
    match_score = sum(a.get('match_rate', 0) for a in audits) / len(audits) * 100
    anomaly_score = min(100, 100 - (sum(len(a.get('anomalies', [])) for a in audits) / len(audits) * 5))
    fraud_score = 100 - (sum(a.get('fraud_risk', 0) for a in audits) / len(audits))
    
    # Weighted score
    efficiency = (match_score * 0.5) + (anomaly_score * 0.3) + (fraud_score * 0.2)
    
    return min(100, max(0, efficiency))

def get_benchmark_data():
    """Get industry benchmark data"""
    # These are sample benchmarks - can be refined with real data
    return {
        'avg_match_rate': 85.5,
        'avg_fraud_risk': 32.0,
        'avg_time_saved': 12.5,
        'top_performer_match': 96.0,
        'top_performer_fraud': 15.0
    }

def generate_analytics_report(audits, firm_name):
    """Generate analytics report as markdown"""
    if not audits:
        return "No audit data available yet. Run some audits to generate analytics."
    
    hours_saved = calculate_time_saved(audits)
    cost_saved = calculate_cost_savings(hours_saved)
    efficiency = get_efficiency_score(audits)
    benchmarks = get_benchmark_data()
    
    report = f"""
# ARAI Analytics Report
## Generated for {firm_name}
*Date: {datetime.now().strftime('%B %d, %Y')}*

---

## Executive Summary

| Metric | Your Firm | Industry Benchmark | Performance |
|--------|-----------|-------------------|-------------|
| Total Audits | {len(audits)} | - | - |
| Time Saved | {hours_saved:.1f} hours | {benchmarks['avg_time_saved']} hours | {'✅ Above' if hours_saved > benchmarks['avg_time_saved'] else '⚠️ Below'} |
| Cost Saved | ${cost_saved:,.0f} | - | - |
| Efficiency Score | {efficiency:.0f}/100 | - | - |

---

## Detailed Metrics

### Match Rate Performance
- **Your Average:** {sum(a.get('match_rate', 0) for a in audits) / len(audits):.1%}
- **Industry Average:** {benchmarks['avg_match_rate']:.1%}
- **Top Performer:** {benchmarks['top_performer_match']:.1%}

### Fraud Risk Management
- **Your Average:** {sum(a.get('fraud_risk', 0) for a in audits) / len(audits):.0f}%
- **Industry Average:** {benchmarks['avg_fraud_risk']:.0f}%
- **Top Performer:** {benchmarks['top_performer_fraud']:.0f}%

---

## Key Insights

1. **Time Savings:** ARAI has saved your firm {hours_saved:.1f} hours, equivalent to ${cost_saved:,.0f} in billable time.

2. **Efficiency Score:** Your overall audit efficiency is {efficiency:.0f}/100. {'This is excellent!' if efficiency > 75 else 'There is room for improvement.'}

3. **Recommendations:**
   - {'Continue your current audit approach' if efficiency > 75 else 'Focus on improving match rates and reducing anomalies'}
   - Run regular audits to track performance trends
   - {'Consider upgrading to Professional plan for additional features' if len(audits) < 50 else 'Your usage is growing - great work!'}

---

*Generated by ARAI - Finance Done Smarter*
"""
    return report

def display_analytics_dashboard(audits, firm_name):
    """Display analytics dashboard in Streamlit"""
    
    if not audits:
        st.info("No audit data available yet. Run some audits to see analytics.")
        return
    
    hours_saved = calculate_time_saved(audits)
    cost_saved = calculate_cost_savings(hours_saved)
    efficiency = get_efficiency_score(audits)
    benchmarks = get_benchmark_data()
    
    # Top metrics row
    st.markdown("### 📊 Performance Overview")
    
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Audits", len(audits))
    col2.metric("Time Saved", f"{hours_saved:.0f} hours", 
                delta=f"${cost_saved:,.0f} saved")
    col3.metric("Efficiency Score", f"{efficiency:.0f}/100",
                delta="Excellent" if efficiency > 75 else "Good")
    col4.metric("Avg Match Rate", f"{sum(a.get('match_rate', 0) for a in audits) / len(audits):.1%}")
    
    st.markdown("---")
    
    # Benchmark comparison
    st.markdown("### 📈 Benchmark Comparison")
    
    col1, col2 = st.columns(2)
    
    with col1:
        # Match rate comparison
        avg_match = sum(a.get('match_rate', 0) for a in audits) / len(audits) * 100
        fig = go.Figure(go.Indicator(
            mode = "gauge+number+delta",
            value = avg_match,
            title = {'text': "Match Rate vs Industry"},
            delta = {'reference': benchmarks['avg_match_rate']},
            gauge = {
                'axis': {'range': [None, 100]},
                'bar': {'color': "#1f77b4"},
                'steps': [
                    {'range': [0, 50], 'color': "#ff6b6b"},
                    {'range': [50, 75], 'color': "#ffa500"},
                    {'range': [75, 100], 'color': "#4ecdc4"}
                ],
                'threshold': {
                    'line': {'color': "red", 'width': 4},
                    'thickness': 0.75,
                    'value': benchmarks['avg_match_rate']
                }
            }
        ))
        fig.update_layout(height=300)
        st.plotly_chart(fig, use_container_width=True)
    
    with col2:
        # Fraud risk comparison
        avg_risk = sum(a.get('fraud_risk', 0) for a in audits) / len(audits)
        fig = go.Figure(go.Indicator(
            mode = "gauge+number+delta",
            value = avg_risk,
            title = {'text': "Fraud Risk vs Industry"},
            delta = {'reference': benchmarks['avg_fraud_risk'], 'position': "bottom"},
            gauge = {
                'axis': {'range': [0, 100]},
                'bar': {'color': "#ffa500"},
                'steps': [
                    {'range': [0, 30], 'color': "#4ecdc4"},
                    {'range': [30, 70], 'color': "#ffa500"},
                    {'range': [70, 100], 'color': "#ff6b6b"}
                ],
                'threshold': {
                    'line': {'color': "red", 'width': 4},
                    'thickness': 0.75,
                    'value': benchmarks['avg_fraud_risk']
                }
            }
        ))
        fig.update_layout(height=300)
        st.plotly_chart(fig, use_container_width=True)
    
    st.markdown("---")
    
    # Monthly trends
    st.markdown("### 📅 Monthly Trends")
    
    monthly = get_monthly_trends(audits)
    if not monthly.empty:
        col1, col2 = st.columns(2)
        
        with col1:
            fig = px.line(monthly, x='Month', y='Avg Match Rate', 
                         title='Match Rate Trend',
                         markers=True)
            fig.update_traces(line_color='#1f77b4')
            st.plotly_chart(fig, use_container_width=True)
        
        with col2:
            fig = px.bar(monthly, x='Month', y='Audit Count',
                        title='Audit Volume',
                        color_discrete_sequence=['#28a745'])
            st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("Run more audits to see monthly trends")
    
    st.markdown("---")
    
    # Export button
    st.markdown("### 📥 Export Report")
    
    if st.button("Generate Analytics Report"):
        report = generate_analytics_report(audits, firm_name)
        st.download_button(
            label="Download Report (Markdown)",
            data=report,
            file_name=f"arai_analytics_{datetime.now().strftime('%Y%m%d')}.md",
            mime="text/markdown"
        )