import yagmail
import streamlit as st
import os
from datetime import datetime

def send_report_email(recipient_email, recipient_name, firm_name, pdf_path, audit_summary):
    try:
        sender_email = st.secrets["EMAIL_SENDER"]
        sender_password = st.secrets["EMAIL_PASSWORD"]
        
        yag = yagmail.SMTP(sender_email, sender_password)
        
        subject = f"ARAI Audit Report - {datetime.now().strftime('%Y-%m-%d')}"
        
        contents = f"""
Dear {recipient_name},

Please find attached the audit report prepared for your firm.

Audit Summary:
- Match Rate: {audit_summary.get('match_rate', 0):.1%}
- Transactions Matched: {audit_summary.get('matched', 0)}
- Unmatched Transactions: {audit_summary.get('unmatched_bank', 0)}
- Fraud Risk Score: {audit_summary.get('fraud_risk', 0):.0f}%
- Anomalies Detected: {audit_summary.get('anomalies', 0)}

This report was generated by ARAI (Audit Risk & AI Intelligence) on behalf of {firm_name}.

For any questions, please contact your audit representative.

Best regards,
{firm_name} Audit Team
---
Powered by ARAI - Finance Done Smarter
        """
        
        yag.send(to=recipient_email, subject=subject, contents=contents, attachments=pdf_path)
        yag.close()
        return True, "Email sent successfully"
        
    except Exception as e:
        return False, str(e)