from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas
from datetime import datetime

def generate_audit_pdf(firm_name, client_name, audit_data, output_path):
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4
    
    primary_color = HexColor('#1f77b4')
    success_color = HexColor('#28a745')
    warning_color = HexColor('#ffc107')
    danger_color = HexColor('#dc3545')
    
    # Cover Page
    c.setFont("Helvetica-Bold", 24)
    c.setFillColor(primary_color)
    c.drawString(50, height - 50, "ARAI")
    
    c.setFont("Helvetica", 10)
    c.setFillColor(HexColor('#666666'))
    c.drawString(50, height - 70, "Audit Risk & AI Intelligence")
    
    c.line(50, height - 85, width - 50, height - 85)
    
    c.setFont("Helvetica-Bold", 18)
    c.setFillColor(HexColor('#000000'))
    c.drawString(50, height - 140, "AUDIT REPORT")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 165, f"Prepared for: {client_name}")
    c.drawString(50, height - 185, f"Prepared by: {firm_name}")
    c.drawString(50, height - 205, f"Date: {datetime.now().strftime('%d %B %Y')}")
    
    # Summary Page
    c.showPage()
    
    c.setFont("Helvetica-Bold", 16)
    c.setFillColor(primary_color)
    c.drawString(50, height - 50, "Executive Summary")
    c.line(50, height - 60, width - 50, height - 60)
    
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(HexColor('#000000'))
    c.drawString(50, height - 100, "Key Findings:")
    
    c.setFont("Helvetica", 11)
    c.drawString(50, height - 125, f"• Match Rate: {audit_data.get('match_rate', 0):.1%}")
    c.drawString(50, height - 145, f"• Transactions Matched: {audit_data.get('matched', 0)}")
    c.drawString(50, height - 165, f"• Unmatched Bank Transactions: {audit_data.get('unmatched_bank', 0)}")
    c.drawString(50, height - 185, f"• Unmatched Ledger Entries: {audit_data.get('unmatched_ledger', 0)}")
    c.drawString(50, height - 205, f"• Anomalies Detected: {audit_data.get('anomalies', 0)}")
    
    fraud_risk = audit_data.get('fraud_risk', 0)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 260, "Risk Assessment:")
    
    if fraud_risk >= 70:
        c.setFillColor(danger_color)
        c.drawString(50, height - 285, f"🔴 HIGH RISK: {fraud_risk:.0f}% fraud probability detected")
    elif fraud_risk >= 40:
        c.setFillColor(warning_color)
        c.drawString(50, height - 285, f"🟡 MEDIUM RISK: {fraud_risk:.0f}% fraud probability detected")
    else:
        c.setFillColor(success_color)
        c.drawString(50, height - 285, f"🟢 LOW RISK: {fraud_risk:.0f}% fraud probability detected")
    
    # Footer
    c.showPage()
    c.setFont("Helvetica", 9)
    c.setFillColor(HexColor('#999999'))
    c.drawString(50, 30, f"Generated by ARAI AI Audit Platform on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    c.drawString(width - 150, 30, "Confidential - For Internal Use")
    
    c.save()
    return output_path