from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas
from datetime import datetime
import urllib.request
from PIL import Image
import io

def generate_audit_pdf(firm_name, client_name, audit_data, output_path, branding=None):
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4
    
    # Use branding colors or defaults
    if branding and branding.get('custom_branding'):
        primary_color_hex = branding.get('primary_color', '#1f77b4')
        secondary_color_hex = branding.get('secondary_color', '#4ecdc4')
        footer_text = branding.get('footer_text', '')
        logo_url = branding.get('logo_url', None)
    else:
        primary_color_hex = '#1f77b4'
        secondary_color_hex = '#4ecdc4'
        footer_text = ''
        logo_url = None
    
    primary_color = HexColor(primary_color_hex)
    secondary_color = HexColor(secondary_color_hex)
    
    # Cover Page
    c.setFont("Helvetica-Bold", 24)
    c.setFillColor(primary_color)
    
    # Add logo if available
    if logo_url:
        try:
            # Download logo from URL
            with urllib.request.urlopen(logo_url) as response:
                logo_data = response.read()
            logo_img = Image.open(io.BytesIO(logo_data))
            
            # Calculate logo position (top right)
            logo_width = 80
            logo_height = int(logo_width * logo_img.height / logo_img.width)
            logo_img = logo_img.resize((logo_width, logo_height), Image.Resampling.LANCZOS)
            
            # Save temporary file
            temp_logo = f"/tmp/logo_{datetime.now().timestamp()}.png"
            logo_img.save(temp_logo)
            
            c.drawImage(temp_logo, width - 100, height - 60, width=logo_width, height=logo_height)
        except:
            pass  # Skip logo if download fails
    
    c.drawString(50, height - 50, "AUDIT REPORT")
    
    c.setFont("Helvetica", 10)
    c.setFillColor(HexColor('#666666'))
    c.drawString(50, height - 70, "Prepared by ARAI AI Audit Platform")
    
    c.line(50, height - 85, width - 50, height - 85)
    
    c.setFont("Helvetica-Bold", 16)
    c.setFillColor(primary_color)
    c.drawString(50, height - 140, f"Prepared for: {client_name}")
    
    c.setFont("Helvetica", 12)
    c.setFillColor(HexColor('#000000'))
    c.drawString(50, height - 165, f"Prepared by: {firm_name}")
    c.drawString(50, height - 185, f"Date: {datetime.now().strftime('%d %B %Y')}")
    
    # Summary Page
    c.showPage()
    
    c.setFont("Helvetica-Bold", 16)
    c.setFillColor(primary_color)
    c.drawString(50, height - 50, "Executive Summary")
    c.line(50, height - 60, width - 50, height - 60)
    
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(HexColor('#000000'))
    c.drawString(50, height - 100, "Key Findings:")
    
    c.setFont("Helvetica", 11)
    c.drawString(50, height - 125, f"• Match Rate: {audit_data.get('match_rate', 0):.1%}")
    c.drawString(50, height - 145, f"• Transactions Matched: {audit_data.get('matched', 0)}")
    c.drawString(50, height - 165, f"• Unmatched Bank Transactions: {audit_data.get('unmatched_bank', 0)}")
    c.drawString(50, height - 185, f"• Unmatched Ledger Entries: {audit_data.get('unmatched_ledger', 0)}")
    c.drawString(50, height - 205, f"• Anomalies Detected: {audit_data.get('anomalies', 0)}")
    
    fraud_risk = audit_data.get('fraud_risk', 0)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 260, "Risk Assessment:")
    
    if fraud_risk >= 70:
        c.setFillColor(HexColor('#dc3545'))
        c.drawString(50, height - 285, f"🔴 HIGH RISK: {fraud_risk:.0f}% fraud probability detected")
    elif fraud_risk >= 40:
        c.setFillColor(HexColor('#ffc107'))
        c.drawString(50, height - 285, f"🟡 MEDIUM RISK: {fraud_risk:.0f}% fraud probability detected")
    else:
        c.setFillColor(secondary_color)
        c.drawString(50, height - 285, f"🟢 LOW RISK: {fraud_risk:.0f}% fraud probability detected")
    
    # Footer
    c.showPage()
    c.setFont("Helvetica", 9)
    c.setFillColor(HexColor('#999999'))
    
    if footer_text:
        c.drawString(50, 30, footer_text)
    else:
        c.drawString(50, 30, f"Generated by ARAI AI Audit Platform on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    
    c.drawString(width - 150, 30, "Confidential - For Internal Use")
    
    c.save()
    return output_path